In [1]:
from sklearn.linear_model import LogisticRegression, LogisticRegressionCV, LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn import svm
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, multilabel_confusion_matrix
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import pickle as pkl
pkl_file = "/home/siu856533724/code/source-code/Social-Networks/Trend-Prediction/Main-Implementation/model_save/trend_pred"

In [2]:
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import make_scorer, f1_score, hamming_loss, log_loss
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [37]:
dataset = pd.read_csv('/home/siu856533724/code/source-code/Social-Networks/Trend-Prediction/DataSet/trend-data/emotion_trend_mapping(updated-D4).csv')

In [38]:
dataset.head()

Unnamed: 0                                               text  \
0           0  Dear Jesus Really Vander Plaats really become ...   
1           1  attack queers sorry Cabal Sanctimonious Hypocr...   
2           2  Unspecified source ImageNanaJPG Thanks uploadi...   
3           3  person status where status abstract concept wi...   
4           4  National Cunt Prevention Board name Norman fro...   

                               trend_type  admiration  amusement     anger  \
0  ['toxic', 'obscene', 'insult', 'hate']    0.040463   0.001738  0.006114   
1                             ['neither']    0.001806   0.001375  0.336123   
2                             ['neither']    0.000987   0.000774  0.034833   
3                             ['obscene']    0.001493   0.000768  0.528994   
4          ['toxic', 'obscene', 'insult']    0.009913   0.000559  0.019684   

   annoyance  approval    caring  confusion  ...  surprise   neutral  \
0   0.025908  0.051705  0.006283   0.067305  ...  0.006851  0.189996   
1   0.317506  0.012453  0.002173   0.006411  ...  0.002444  0.133335   
2   0.036450  0.004978  0.001220   0.017123  ...  0.002954  0.821627   
3   0.254255  0.010222  0.004622   0.015273  ...  0.001391  0.092313   
4   0.045652  0.024483  0.008476   0.114395  ...  0.006786  0.532468   

   approval.1  toxic  obscene  insult  threat  hate  offensive  neither  
0         0.0    1.0      1.0     1.0     0.0   1.0        0.0        0  
1         0.0    0.0      0.0     0.0     0.0   0.0        0.0        1  
2         0.0    0.0      0.0     0.0     0.0   0.0        0.0        1  
3         0.0    0.0      1.0     0.0     0.0   0.0        0.0        0  
4         0.0    1.0      1.0     1.0     0.0   0.0        0.0        0  

[5 rows x 39 columns]

In [39]:
dataset.shape

(29853, 39)

In [40]:
dataset.drop(['Unnamed: 0'], axis=1, inplace=True)

In [41]:
high_corr_features = ['admiration', 'anger', 'annoyance', 'approval', 'confusion', 'curiosity', 'desire', 'disappointment', 'disapproval', 
                      'disgust', 'excitement', 'fear', 'gratitude', 'grief', 'joy', 'nervousness', 'neutral', 'optimism', 'pride', 'realization', 
                      'relief', 'remorse', 'sadness']
# print(high_corr_features)

In [42]:
dataset.head()

text  \
0  Dear Jesus Really Vander Plaats really become ...   
1  attack queers sorry Cabal Sanctimonious Hypocr...   
2  Unspecified source ImageNanaJPG Thanks uploadi...   
3  person status where status abstract concept wi...   
4  National Cunt Prevention Board name Norman fro...   

                               trend_type  admiration  amusement     anger  \
0  ['toxic', 'obscene', 'insult', 'hate']    0.040463   0.001738  0.006114   
1                             ['neither']    0.001806   0.001375  0.336123   
2                             ['neither']    0.000987   0.000774  0.034833   
3                             ['obscene']    0.001493   0.000768  0.528994   
4          ['toxic', 'obscene', 'insult']    0.009913   0.000559  0.019684   

   annoyance  approval    caring  confusion  curiosity  ...  surprise  \
0   0.025908  0.051705  0.006283   0.067305   0.497370  ...  0.006851   
1   0.317506  0.012453  0.002173   0.006411   0.005952  ...  0.002444   
2   0.036450  0.004978  0.001220   0.017123   0.024646  ...  0.002954   
3   0.254255  0.010222  0.004622   0.015273   0.015281  ...  0.001391   
4   0.045652  0.024483  0.008476   0.114395   0.045156  ...  0.006786   

    neutral  approval.1  toxic  obscene  insult  threat  hate  offensive  \
0  0.189996         0.0    1.0      1.0     1.0     0.0   1.0        0.0   
1  0.133335         0.0    0.0      0.0     0.0     0.0   0.0        0.0   
2  0.821627         0.0    0.0      0.0     0.0     0.0   0.0        0.0   
3  0.092313         0.0    0.0      1.0     0.0     0.0   0.0        0.0   
4  0.532468         0.0    1.0      1.0     1.0     0.0   0.0        0.0   

   neither  
0        0  
1        1  
2        1  
3        0  
4        0  

[5 rows x 38 columns]

In [43]:
featurs = dataset.iloc[:, 2:-8]
target = dataset.iloc[:, -8:]

In [44]:
featurs.head()

admiration  amusement     anger  annoyance  approval    caring  confusion  \
0    0.040463   0.001738  0.006114   0.025908  0.051705  0.006283   0.067305   
1    0.001806   0.001375  0.336123   0.317506  0.012453  0.002173   0.006411   
2    0.000987   0.000774  0.034833   0.036450  0.004978  0.001220   0.017123   
3    0.001493   0.000768  0.528994   0.254255  0.010222  0.004622   0.015273   
4    0.009913   0.000559  0.019684   0.045652  0.024483  0.008476   0.114395   

   curiosity    desire  disappointment  ...      love  nervousness  optimism  \
0   0.497370  0.013709        0.004352  ...  0.000502     0.000344  0.027791   
1   0.005952  0.000429        0.013386  ...  0.000169     0.001365  0.001365   
2   0.024646  0.000479        0.003308  ...  0.000126     0.000342  0.000519   
3   0.015281  0.000821        0.005845  ...  0.000187     0.000658  0.002404   
4   0.045156  0.007880        0.010826  ...  0.000190     0.000956  0.021486   

      pride  realization    relief   remorse   sadness  surprise   neutral  
0  0.007960     0.021605  0.001311  0.000575  0.000499  0.006851  0.189996  
1  0.000586     0.005943  0.000414  0.000987  0.002704  0.002444  0.133335  
2  0.000565     0.002335  0.000198  0.000371  0.001146  0.002954  0.821627  
3  0.000674     0.003863  0.000325  0.000800  0.001137  0.001391  0.092313  
4  0.018226     0.050623  0.000810  0.004485  0.003249  0.006786  0.532468  

[5 rows x 28 columns]

In [45]:
target.head()

approval.1  toxic  obscene  insult  threat  hate  offensive  neither
0         0.0    1.0      1.0     1.0     0.0   1.0        0.0        0
1         0.0    0.0      0.0     0.0     0.0   0.0        0.0        1
2         0.0    0.0      0.0     0.0     0.0   0.0        0.0        1
3         0.0    0.0      1.0     0.0     0.0   0.0        0.0        0
4         0.0    1.0      1.0     1.0     0.0   0.0        0.0        0

In [46]:
# Splitting the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(featurs, target, test_size=0.2, random_state=42)

In [12]:
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()

# # Fit the scaler on the training data and transform the features
# X_train= scaler.fit_transform(X_train)

In [47]:
# Create a scoring function
scoring = {
    'F1 Micro': make_scorer(f1_score, average='micro'),
    'Loss': make_scorer(log_loss)
}

## RandomForest

In [14]:
# from sklearn.model_selection import GridSearchCV
# # Create the parameter grid based on the results of random search 
# params = {
#     'n_estimators': [50, 100],
#     'max_depth': [None, 10, 20]
# }
# rf = RandomForestClassifier()
# rmd_forest_grid = GridSearchCV(estimator = rf, param_grid = params, cv = 2, scoring=scoring, refit='F1 Micro', n_jobs = -1, verbose=2)
# # train
# rmd_forest_grid.fit(X_train, y_train)
# # predict
# grid_pred = rmd_forest_grid.predict(X_test)
# print("Accuracy = ", accuracy_score(y_test, grid_pred))

In [48]:
from sklearn.datasets import make_multilabel_classification
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import make_scorer, hamming_loss
from sklearn.tree import DecisionTreeClassifier

# **XGBoost Classifier with MultiOutputClassifier and GridSearch**

In [49]:

# Define the XGBoost classifier
xgb = XGBClassifier()

# Parameters to tune for XGBoost
params_xgb = {
    'n_estimators': [1000],
    'max_depth': [15],
}

# Define the parameter grid including learning rate and loss function
param_grid = {
    'learning_rate': [0.1],  # Adjust these values as needed
    'objective': ['binary:logistic'],  # Examples of loss functions
    # Other hyperparameters to tune
    'max_depth': [10, 20],
    'n_estimators': [700, 1000]
    # Add other parameters to optimize
}

# Create the GridSearchCV for XGBoost
grid_search_xgb = GridSearchCV(xgb, param_grid, cv=5, verbose=2, n_jobs=-1)
grid_search_xgb.fit(X_train, y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits


[CV] END learning_rate=0.1, max_depth=10, n_estimators=700, objective=binary:logistic; total time=11.5min
[CV] END learning_rate=0.1, max_depth=10, n_estimators=700, objective=binary:logistic; total time=11.5min
[CV] END learning_rate=0.1, max_depth=10, n_estimators=700, objective=binary:logistic; total time=11.5min
[CV] END learning_rate=0.1, max_depth=10, n_estimators=700, objective=binary:logistic; total time=11.5min
[CV] END learning_rate=0.1, max_depth=10, n_estimators=700, objective=binary:logistic; total time=11.8min
[CV] END learning_rate=0.1, max_depth=10, n_estimators=1000, objective=binary:logistic; total time=16.2min
[CV] END learning_rate=0.1, max_depth=10, n_estimators=1000, objective=binary:logistic; total time=16.2min
[CV] END learning_rate=0.1, max_depth=10, n_estimators=1000, objective=binary:logistic; total time=16.2min
[CV] END learning_rate=0.1, max_depth=10, n_estimators=1000, objective=binary:logistic; total time=16.2min
[CV] END learning_rate=0.1, max_depth=10, 

In [50]:
print("Best parameters for XGBoost:")
print(grid_search_xgb.best_params_)

print("Classification report on test set:")
y_pred_xgb = grid_search_xgb.predict(X_test)
print(multilabel_confusion_matrix(y_test, y_pred_xgb))

Best parameters for XGBoost:
{'learning_rate': 0.1, 'max_depth': 20, 'n_estimators': 700, 'objective': 'binary:logistic'}
Classification report on test set:
[[[5371   88]
  [ 503    9]]

 [[1367 1560]
  [1403 1641]]

 [[3995  293]
  [1589   94]]

 [[4141  239]
  [1519   72]]

 [[5874   11]
  [  86    0]]

 [[5312   90]
  [ 563    6]]

 [[4958  134]
  [ 857   22]]

 [[4755  151]
  [1030   35]]]


In [51]:
print("Training Acc: ", grid_search_xgb.score(X_train, y_train))
# print("Test Acc: ", grid_search_xgb.score(X_test, y_test))

Training Acc:  0.872414370655724


In [52]:
pred_proba = grid_search_xgb.predict_proba(X_train)
pred_proba[0]
# print(classification_report(y_test, pred_proba))

array([6.1769114e-04, 5.0359696e-01, 4.9137542e-01, 5.0174773e-01,
       4.9070087e-01, 4.9660531e-01, 3.7934605e-04, 9.6876064e-04],
      dtype=float32)

In [53]:
import os
pkl_file = "/home/siu856533724/code/source-code/Social-Networks/Trend-Prediction/Main-Implementation/model_save/trend_pred"
pickle = pkl.dump(grid_search_xgb, open(os.path.join(pkl_file, 'grid_xgb.pickle'), 'wb'))

In [20]:
# import numpy as np
# from sklearn.datasets import make_classification
# from sklearn.model_selection import train_test_split
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.linear_model import LogisticRegression
# from sklearn.ensemble import StackingClassifier
# import xgboost as xgb

# # Initialize base models
# base_models = [
#     ('rf', RandomForestClassifier(n_estimators=100, random_state=42)),
#     ('lr', LogisticRegression(max_iter=1000, random_state=42))
# ]

# # Initialize XGBoost model
# xgb_model = xgb.XGBClassifier(max_depth=15, n_estimators=200, learning_rate=0.1, random_state=42)

# multilabel = MultiOutputClassifier(xgb_model)

# # StackingClassifier with XGBoost as final_estimator
# stacking_model = StackingClassifier(estimators=base_models, final_estimator=multilabel)

# # Fit the stacking model
# stacking_model.fit(X_train, y_train)

# # Evaluate on test set
# accuracy = stacking_model.score(X_test, y_test)
# print("Accuracy on test set (Stacking):", accuracy)

In [21]:
# pred_proba = stacking_model.predict_proba(X_test)
# print("Prediction Probability: ", pred_proba)
# # print(classification_report(y_test, pred_proba))

# **XGB Classifier with MultiOutputClassifier, Base Decision Tree and GridSearch**

In [22]:

# # Define the XGBoost classifier
# xgb = MultiOutputClassifier(XGBClassifier(base_estimator=DecisionTreeClassifier(max_depth=3), n_estimators=100, random_state=42))

# # Parameters to tune for XGBoost
# params_xgb = {
#     'estimator__base_estimator__max_depth': [5, 10, 15],
#     'estimator__n_estimators': [50, 100, 150],
#     'estimator__max_depth': [5, 10, 15]
# }

# # Create the GridSearchCV for XGBoost
# grid_search_xgb = GridSearchCV(xgb, params_xgb, scoring=scoring, cv=2, refit='F1 Micro', verbose=2)
# grid_search_xgb.fit(X_train, y_train)

# print("Best parameters for XGBoost:")
# print(grid_search_xgb.best_params_)

# print("Classification report on test set:")
# y_pred_xgb = grid_search_xgb.predict(X_test)
# print(classification_report(y_test, y_pred_xgb))

In [23]:
# # Evaluate performance (you can use different metrics for multilabel classification)
# accuracy = accuracy_score(y_test, y_pred_xgb)
# print(f"Accuracy: {accuracy}")
# print("Training Acc: ", grid_search_xgb.score(X_train, y_train))
# print("Test Acc: ", grid_search_xgb.score(X_test, y_test))

# **AdaBoost Classifier with MultiOutputClassifier and GridSearch**

In [24]:
# Create AdaBoost classifier
ada_classifier = AdaBoostClassifier(random_state=42)

# Create MultiOutputClassifier using AdaBoost
multioutput_classifier = MultiOutputClassifier(ada_classifier)

# Define the parameter grid for GridSearch
param_grid = {
    'estimator__n_estimators': [700, 1000],
    'estimator__learning_rate': [0.1, 0.3, 0.5]
}

# Perform GridSearchCV
grid_search = GridSearchCV(multioutput_classifier, param_grid, scoring=scoring, cv=5, refit='F1 Micro', verbose=2)
grid_search.fit(X_train, y_train)

# Get the best parameters and score
print("Best parameters found:")
print(grid_search.best_params_)
print("Best score:", grid_search.best_score_)


Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] END estimator__learning_rate=0.1, estimator__n_estimators=700; total time=12.4min
[CV] END estimator__learning_rate=0.1, estimator__n_estimators=700; total time=12.5min
[CV] END estimator__learning_rate=0.1, estimator__n_estimators=700; total time=12.5min
[CV] END estimator__learning_rate=0.1, estimator__n_estimators=700; total time=12.5min
[CV] END estimator__learning_rate=0.1, estimator__n_estimators=700; total time=12.5min
[CV] END estimator__learning_rate=0.1, estimator__n_estimators=1000; total time=17.8min
[CV] END estimator__learning_rate=0.1, estimator__n_estimators=1000; total time=17.7min
[CV] END estimator__learning_rate=0.1, estimator__n_estimators=1000; total time=17.8min
[CV] END estimator__learning_rate=0.1, estimator__n_estimators=1000; total time=17.8min
[CV] END estimator__learning_rate=0.1, estimator__n_estimators=1000; total time=17.8min
[CV] END estimator__learning_rate=0.3, estimator__n_estimators=70

In [32]:
# Evaluate on test set
y_pred = grid_search.predict_proba(X_test)

NotFittedError: This GridSearchCV instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [25]:
# Evaluate performance (you can use different metrics for multilabel classification)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print("Training Acc: ", grid_search.score(X_train, y_train))
print("Test Acc: ", grid_search.score(X_test, y_test))

Accuracy: 0.0014027119096920713
Training Acc:  0.00998461829074129
Test Acc:  0.0031290461804056972


In [26]:
pred_proba = grid_search.predict_proba(X_test)
print("Prediction Probability: ", pred_proba)
# print(classification_report(y_test, pred_proba))

Prediction Probability:  [array([[0.50056444, 0.49943556],
       [0.50058549, 0.49941451],
       [0.50056181, 0.49943819],
       ...,
       [0.5004702 , 0.4995298 ],
       [0.5005403 , 0.4994597 ],
       [0.50051319, 0.49948681]]), array([[0.50069239, 0.49930761],
       [0.50092554, 0.49907446],
       [0.50074948, 0.49925052],
       ...,
       [0.50069992, 0.49930008],
       [0.50063255, 0.49936745],
       [0.50071187, 0.49928813]]), array([[0.5010137 , 0.4989863 ],
       [0.50118454, 0.49881546],
       [0.50098471, 0.49901529],
       ...,
       [0.50101784, 0.49898216],
       [0.50096689, 0.49903311],
       [0.50109439, 0.49890561]]), array([[0.50109298, 0.49890702],
       [0.50129886, 0.49870114],
       [0.50117994, 0.49882006],
       ...,
       [0.50112853, 0.49887147],
       [0.50108662, 0.49891338],
       [0.50111298, 0.49888702]]), array([[0.50306489, 0.49693511],
       [0.50455038, 0.49544962],
       [0.51187922, 0.48812078],
       ...,
       [0.50344

# **AdaBoost Classifier with Multi Output, Base Decision Tree, GridSearch**

In [27]:
from sklearn.datasets import make_multilabel_classification
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import make_scorer, hamming_loss
from sklearn.tree import DecisionTreeClassifier

# Create AdaBoost classifier
ada_classifier = AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=3), n_estimators=100, random_state=42)

# Create MultiOutputClassifier using AdaBoost
multioutput_classifier = MultiOutputClassifier(ada_classifier)

# Define the parameter grid for GridSearch
param_grid = {
    'estimator__base_estimator__max_depth': [15, 20, 25],
    'estimator__n_estimators': [500, 700, 1000],
    'estimator__learning_rate': [0.01, 0.1, 0.3]
}

# Create scorer for multilabel classification (use appropriate metric)
# scorer = make_scorer(log_loss)

# Perform GridSearchCV
grid_search = GridSearchCV(multioutput_classifier, param_grid, scoring=scoring, cv=5, refit='F1 Micro', verbose=2)
grid_search.fit(X_train, y_train)

# Get the best parameters and score
print("Best parameters found:")
print(grid_search.best_params_)
print("Best score:", grid_search.best_score_)

# Evaluate on test set
y_pred = grid_search.predict(X_test)

Fitting 5 folds for each of 27 candidates, totalling 135 fits
[CV] END estimator__base_estimator__max_depth=15, estimator__learning_rate=0.01, estimator__n_estimators=500; total time=100.5min
[CV] END estimator__base_estimator__max_depth=15, estimator__learning_rate=0.01, estimator__n_estimators=500; total time=100.7min
[CV] END estimator__base_estimator__max_depth=15, estimator__learning_rate=0.01, estimator__n_estimators=500; total time=100.4min
[CV] END estimator__base_estimator__max_depth=15, estimator__learning_rate=0.01, estimator__n_estimators=500; total time=100.7min
[CV] END estimator__base_estimator__max_depth=15, estimator__learning_rate=0.01, estimator__n_estimators=500; total time=101.1min
[CV] END estimator__base_estimator__max_depth=15, estimator__learning_rate=0.01, estimator__n_estimators=700; total time=141.5min
[CV] END estimator__base_estimator__max_depth=15, estimator__learning_rate=0.01, estimator__n_estimators=700; total time=140.6min
[CV] END estimator__base_est

KeyboardInterrupt: 

In [ ]:
# Evaluate performance (you can use different metrics for multilabel classification)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print("Training Acc: ", grid_search.score(X_train, y_train))
print("Test Acc: ", grid_search.score(X_test, y_test))

In [ ]:
pred_proba = grid_search.predict_proba(X_test)
print("Prediction Probability: ", pred_proba)
# print(classification_report(y_test, pred_proba))

# **LGBM Classifier with MultiOutputClass, and GridSearch**

In [ ]:
from lightgbm import LGBMClassifier
# Define the classifier
lgbm = LGBMClassifier()

# Create MultiOutputClassifier using AdaBoost
multioutput_classifier = MultiOutputClassifier(lgbm)

# Define the parameters for grid search
param_grid = {
    'estimator__num_leaves': [20, 50],  # Vary the number of leaves
    'estimator__max_depth': [15,20,25],  # Vary the maximum depth of trees
    'estimator__n_estimators': [500, 700, 1000],  # Number of boosting iterations
    'estimator__learning_rate': [0.01, 0.1, 0.3]  # Learning rate for boosting
}

# Create a scoring function
# scoring = {
#     'F1 Micro': make_scorer(f1_score, average='micro'),
#     'Hamming Loss': make_scorer(hamming_loss)
# }

# Perform GridSearchCV
grid_search = GridSearchCV(multioutput_classifier, param_grid=param_grid, scoring=scoring, cv=5, refit='F1 Micro', verbose=2)
grid_search.fit(X_train, y_train)

# Get the best parameters and evaluate on the test set
best_params = grid_search.best_params_
print("Best parameters:", best_params)

y_pred = grid_search.predict(X_test)
# Evaluate on the test set
# Example: print classification_report(y_test, y_pred)

In [ ]:
# Evaluate performance (you can use different metrics for multilabel classification)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print("Training Acc: ", grid_search.score(X_train, y_train))
print("Test Acc: ", grid_search.score(X_test, y_test))

In [ ]:
pred_proba = grid_search.predict_proba(X_test)
print("Prediction Probability: ", pred_proba)
# print(classification_report(y_test, pred_proba))

# **GradientBoostingClassifier with MultiOutputClassifer and GridSearch**

In [ ]:
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import make_scorer, f1_score, hamming_loss
from sklearn.preprocessing import MultiLabelBinarizer

# Initialize GradientBoostingClassifier
clf = GradientBoostingClassifier()
# Create MultiOutputClassifier using AdaBoost
multioutput_classifier = MultiOutputClassifier(clf)

# Parameters to tune
params = {
    'estimator__n_estimators': [500, 700, 1000],
    'estimator__max_depth': [15, 20, 25],
    'estimator__learning_rate': [0.01, 0.1, 0.3]
}

# # Create a scoring function
# scoring = {
#     'F1 Micro': make_scorer(f1_score, average='micro'),
#     'Loss': make_scorer(log_loss)
# }

# Apply GridSearchCV
grid_search = GridSearchCV(multioutput_classifier, params, scoring=scoring, cv=5, refit='F1 Micro', verbose=2)
grid_search.fit(X_train, y_train)

print("Best parameters:")
print(grid_search.best_params_)

# Evaluation on test set
y_pred = grid_search.predict(X_test)

In [ ]:
# Evaluate performance (you can use different metrics for multilabel classification)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print("Training Acc: ", grid_search.score(X_train, y_train))
print("Test Acc: ", grid_search.score(X_test, y_test))

In [ ]:
pred_proba = grid_search.predict_proba(X_test)
print("Prediction Probability: ", pred_proba)
# print(classification_report(y_test, pred_proba))

## Decision Tree

In [ ]:
from sklearn import decomposition, datasets
from sklearn import tree
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler

In [ ]:
std_slc = StandardScaler()
pca = decomposition.PCA()
dec_tree = tree.DecisionTreeClassifier()
pipe = Pipeline(steps=[('std_slc', std_slc),
                           ('pca', pca),
                           ('dec_tree', dec_tree)])

In [ ]:
n_components = list(range(1, X_train.shape[1]+1, 1))
criterion = ['gini', 'entropy']
max_depth = [2,4,6,8,10,12]
parameters = dict(pca__n_components=n_components,
                      dec_tree__criterion=criterion,
                      dec_tree__max_depth=max_depth)

In [ ]:
clf_GS = GridSearchCV(pipe, parameters)
clf_GS.fit(X_train, y_train)
dtPreds = clf_GS.predict(X_test)

In [ ]:
cr = classification_report(y_test, dtPreds)
print(cr) 
# write_log("DecisionTree-Grid", cr)

In [ ]:
# pickle = pkl.dump(dtClassifier, open(os.path.join(pkl_file, 'decision_tree.pickle'), 'wb'))

## TabNetClassification

In [ ]:
from pytorch_tabnet.tab_model import TabNetClassifier

# Initialize TabNetClassifier model
clf = TabNetClassifier()  # You can set various parameters here

# Fit the model on the training data
clf.fit(
    X_train=X_train.values,
    y_train=y_train,
    eval_set=[(X_test.values, y_test)],
    patience=10,  # Early stopping patience
    max_epochs=100  # Maximum number of training epochs
)

# Predict on test data
y_pred_proba = clf.predict_proba(X_test.values)

In [ ]:
y_pred_proba